// export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
// export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';

export const SET_POKE_SHINY = "SET_POKE_SHINY";

// SET CONTENT////////////////////////////////////////////////////////////
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_POKE_DETAIL = "SET_POKE_DETAIL";
// export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';

// SET SHOPPING CART/////////////////////////////////////////////////////////////////
export const ADD_BAG_ITEM = "ADD_BAG_ITEM";
// export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_BAG_ITEM = "REMOVE_BAG_ITEM";
// export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const EMPTY_CART = "EMPTY_CART"

// FEED FIREBASE POKES////////////////////////////////////////////////////////////
export const BEGIN_POKES_FEED = "BEGIN_POKES_FEED";
export const SUCCESS_POKES_FEED = "SUCCESS_POKES_FEED";
export const FAIL_POKES_FEED = "FAIL_POKES_FEED_REQUEST";

// REQUEST FIREBASE POKES
export const BEGIN_POKES_REQUEST = "BEGIN_POKES_REQUEST";
export const SUCCESS_POKES_REQUEST = "SUCCESS_POKES_REQUEST";
export const FAIL_POKES_REQUEST = "FAIL_POKES_REQUEST";

// SORT BAR
export const SET_SORTBAR_ACTIVETYPE = "SET_SORTBAR_ACTIVETYPE";
export const BEGIN_SORTBAR_REQUEST = "BEGIN_SORTBAR_REQUEST";
export const SUCCESS_SORTBAR_REQUEST = "SUCCESS_SORTBAR_REQUEST";
export const RESET_SORTBAR_ACTIVETYPE = "RESET_SORTBAR_ACTIVETYPE";

// ============================

// SEND COMMENT
export const SEND_COMMENT = "SEND_COMMENTS";










// ========================



// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

// UPDATE USER INFO
export const BEGIN_UPDATE_USERINFO = "BEGIN_UPDATE_USERINFO";
export const SUCCESS_UPDATE_USERINFO = "SUCCESS_UPDATE_USERINFO";
export const FAIL_UPDATE_USERINFO = "FAIL_UPDATE_USERINFO";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// CREATE ORDER
export const BEGIN_ORDER_CREATE = 'BEGIN_ORDER_CREATE';
export const SUCCESS_ORDER_CREATE = 'SUCCESS_ORDER_CREATE';
export const FAIL_ORDER_CREATE = 'FAIL_ORDER_CREATE';
export const RESET_ORDER = 'RESET_ORDER';

// PAY ORDER
export const BEGIN_ORDER_PAY = 'BEGIN_ORDER_PAY';
export const SUCCESS_ORDER_PAY = 'SUCCESS_ORDER_PAY';
export const FAIL_ORDER_PAY = 'FAIL_ORDER_PAY';
export const RESET_ORDER_PAY = 'RESET_ORDER_PAY';

// GET ORDER DETAIL
export const BEGIN_ORDER_DETAIL = 'BEGIN_ORDER_DETAIL';
export const SUCCESS_ORDER_DETAIL = 'SUCCESS_ORDER_DETAIL';
export const FAIL_ORDER_DETAIL = 'FAIL_ORDER_DETAIL';


// GET ORDERS LIST
export const BEGIN_ORDERS_REQUEST = 'BEGIN_ORDERS_REQUEST'
export const SUCCESS_ORDERS_REQUEST = 'SUCCESS_ORDERS_REQUEST';
export const FAIL_ORDERS_REQUEST = 'FAIL_ORDERS_REQUEST';